version: '3'
services:
  postgres:
    image: postgres
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    restart: always


  rabbitmq:
    image: rabbitmq:3-management
    network_mode: host
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    image: redis
    network_mode: host
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always


volumes:
  postgres:

